import os

BOOTSTRAP_SERVER = os.getenv("BOOTSTRAP_SERVER")
COMSUMER_TOPIC = [os.getenv("COMSUMER_TOPIC")]
CONSUMER_GROUP_ID = os.getenv("CONSUMER_GROUP_ID")
MONGO_HOST = os.getenv("MONGO_HOST")
DB_NAME = os.getenv("DB_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")
